server:
  port: 8080
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false
    path: /error

spring:
  datasource:
    url: jdbc:mysql://paytool.cp0scs4c4gvc.us-east-2.rds.amazonaws.com:3306/paytool?createDatabaseIfNotExist=true&useSSL=true&requireSSL=true
    username: admin
    password: 1057555034
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC
  security:
    user:
      name: admin
      password: secret
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client.id}
            scope:
              - email
              - profile

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  thymeleaf:
    enabled: false
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**
  graphql:
    websocket:
      path: /graphql
      allowed-origins: "ws://localhost:3000"
      connection-init-timeout: 5000
      init-timeout: 5000
      subscription:
        keep-alive:
          enabled: true
          interval: 30s
    graphiql:
      enabled: true
      path: /graphiql
    schema:
      printer:
        enabled: true
    path: /graphql
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600
  subscription:
    enabled: true
    transport: websocket
  websocket:
    max-text-message-size: 128KB
    max-binary-message-size: 128KB
    allowed-origins: "http://localhost:3000"
    path: /graphql

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
  path: /graphql
  graphiql:
    enabled: true
    path: /graphiql
    props:
      resources:
        query: /graphql/query.graphql
        defaultQuery: |
          query {
            hello
          }
  playground:
    enabled: true
    path: /playground
  schema:
    printer:
      enabled: true
  tools:
    schema-location-pattern: "**/*.graphqls"

jwt:
  secret: "this-is-a-very-long-random-secret-key-must-be-at-least-64-characters-long-1234567890"
  expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    org.springframework.security: DEBUG
    com.paytool: DEBUG

google:
  client:
    id: 211473285848-tptiv712dk23v369emgamq2iocg3e0he.apps.googleusercontent.com
