server:
  port: 8080
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false
    path: /error

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paytool?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  thymeleaf:
    enabled: false
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
  graphiql:
    enabled: true
    path: /graphiql
    props:
      resources:
        query: /graphql/query.graphql
        defaultQuery: |
          query {
            hello
          }
  playground:
    enabled: true
    path: /playground
  schema:
    printer:
      enabled: true
  tools:
    schema-location-pattern: "**/*.graphqls"

jwt:
  secret: your-secret-key-here-must-be-at-least-32-characters
  expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    org.springframework.security: DEBUG
    com.paytool: DEBUG 