server:
  port: 8080
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false
    path: /error

spring:
  datasource:
    url: jdbc:mysql://paytool.cp0scs4c4gvc.us-east-2.rds.amazonaws.com:3306/paytool?createDatabaseIfNotExist=true
    username: admin
    password: 1057555034
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  thymeleaf:
    enabled: false
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**
  graphql:
    websocket:
      path: /graphql
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client.id}
            scope:
              - email
              - profile

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
  graphiql:
    enabled: true
    path: /graphiql
    props:
      resources:
        query: /graphql/query.graphql
        defaultQuery: |
          query {
            hello
          }
  playground:
    enabled: true
    path: /playground
  schema:
    printer:
      enabled: true
  tools:
    schema-location-pattern: "**/*.graphqls"

jwt:
  secret: "this-is-a-very-long-random-secret-key-must-be-at-least-64-characters-long-1234567890"
  expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    org.springframework.security: DEBUG
    com.paytool: DEBUG

google:
  client:
    id: 211473285848-tptiv712dk23v369emgamq2iocg3e0he.apps.googleusercontent.com